Implement ESI Vars
fastly/esi pull request #32
Opened 2024-12-04 14:13 UTC by tyler

- [x] Basic variable assignment (esi:assign)
- [x] Short form esi:vars
- [ ] Long form esi:vars

2024-12-04 20:38 UTC, tyler commented
Note to self: add string and book type coercion for EvalResult types

2024-12-15 22:04 UTC, vagetman approved these changes

2025-01-06 11:06 UTC, kailan requested changes
Really pleased with this, thanks so much both for your hard work. Just a few areas to address in regards to error handling but I'm happy for this to be released once the `println`s are gone.

2025-01-06 11:06 UTC, kailan commented on esi/src/parse.rs
>  where
This function signature is getting pretty complex but we can leave it for now as it's not part of the public API surface and there is a parser rework in progress.

2025-01-06 11:06 UTC, kailan commented on esi/src/parse.rs
> +    };
This parsing pattern appears a few times in this file but, again, we can leave that for the parser rework.

2025-01-06 11:06 UTC, kailan commented on esi/src/lib.rs
> +            // TODO: the 'name' here might have a subfield, we need to parse it
Is this something that needs to be addressed before release?

2025-01-06 11:06 UTC, kailan commented on esi/src/lib.rs
> +            println!("Shouldn't be possible to get a When tag here");
Should this throw an error?

2025-01-06 11:06 UTC, kailan commented on esi/src/lib.rs
> +                    println!("Somehow got something other than a When in a Choose: {when:?}",);
Error?

2025-01-06 11:06 UTC, kailan commented on esi/src/lib.rs
> +            println!("Shouldn't be possible to get a When tag here");
If not we should at least avoid `println` and use the logging macros.

2025-01-06 11:06 UTC, kailan commented on esi/src/expression.rs
> +mod tests {
The tests are a large part of this file, I wonder if it's worth extracting them into the `tests` directory.

2025-01-06 11:06 UTC, kailan commented on esi/src/expression.rs
> +            println!("Error while evaluating interpolated expression: {e}");
Should this throw an error?
Avoid `println`

2025-01-06 11:07 UTC, kailan commented on esi/src/expression.rs
> +mod tests {
Not a blocker

2025-01-13 20:13 UTC, tyler commented on esi/src/expression.rs
> +mod tests {
Yeah i was wondering about this. I kind of like having most of them in the file because they use functions that aren't public. But it is a lot. Not super sure.

2025-01-13 20:20 UTC, tyler commented on esi/src/expression.rs
> +            println!("Error while evaluating interpolated expression: {e}");
Removed the println and explained why we eat the error.

2025-01-13 20:20 UTC, tyler commented on esi/src/lib.rs
> +                    println!("Somehow got something other than a When in a Choose: {when:?}",);
Should be unreachable, so marked it as such.

2025-01-13 20:21 UTC, tyler commented on esi/src/lib.rs
> +            // TODO: the 'name' here might have a subfield, we need to parse it
nah, I think that can wait for the parser refactor

2025-01-15 10:21 UTC, kailan approved these changes
This is good to go! Thanks again. Really pleased about this.

2025-01-15 10:22 UTC, merged